# Server
server:
  port: 8080


# Spring Boot
spring:
  application:
    name: CurrencyMateSrv
  main:
    banner-mode: console
    lazy-initialization: true
  profiles:
    default: dev
  jackson:
    time-zone: ${APP_TIME_ZONE:UTC}


# Feign (Spring Cloud)
feign:
  client:
    config:
      default:
        logger-level: FULL
        connect-timeout: 5000 # ms
        read-timeout: 15000 # ms


# Logging
logging:
  level:
    root: INFO
    dev.sgd.currencymate: INFO
    org.springframework: INFO
    feign.client: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# Resilience4j (Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50 # %
        wait-duration-in-open-state: 30000 # ms
        slow-call-rate-threshold: 50 # %
        slow-call-duration-threshold: 3000 # ms
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 2000 # ms


# Actuator
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}


# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: v1
      paths-to-match: /api/v1/**
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    info:
      title: Currency Mate Srv API
      version: 1.0.0
      description: Currency Mate Srv REST API for getting currencies (crypto and fiat) exchange rates (current and time series) using different providers
      contact:
        name: Support
        email: vladimir.alekseev.dev@gmail.com


app:
  adapter:
    alphavantage:
      url: ${EXT_ALPHAVANTAGE_URL:https://www.alphavantage.co}
      apiKey: ${EXT_ALPHAVANTAGE_API_KEY:apikey}
      connectTimeoutMs: ${EXT_ALPHAVANTAGE_CONNECT_TIMEOUT:10000} # ms
      readTimeoutMs: ${EXT_ALPHAVANTAGE_READ_TIMEOUT:30000} # ms
      retryMaxAttempts: ${EXT_ALPHAVANTAGE_RETRY_ATTEMPTS:5}
      retryBackoffDelayMs: ${EXT_ALPHAVANTAGE_RETRY_DELAY:2000} # ms
    exchangerate:
      url: ${EXT_EXCHANGERATE_URL:https://v6.exchangerate-api.com/v6}
      apiKey: ${EXT_EXCHANGERATE_API_KEY:apikey}
      connectTimeoutMs: ${EXT_EXCHANGERATE_CONNECT_TIMEOUT:10000} # ms
      readTimeoutMs: ${EXT_EXCHANGERATE_READ_TIMEOUT:30000} # ms
      retryMaxAttempts: ${EXT_EXCHANGERATE_RETRY_ATTEMPTS:5}
      retryBackoffDelayMs: ${EXT_EXCHANGERATE_RETRY_DELAY:2000} # ms