# Server
server:
  port: 8080

# Spring Boot
spring:
  application:
    name: CurrencyMate
  main:
    banner-mode: console
    lazy-initialization: true
  profiles:
    default: dev
  jackson:
    time-zone: ${APP_TIME_ZONE:UTC}

# Logging
logging:
  level:
    root: INFO
    dev.sgd.currencymate: DEBUG
    org.springframework: DEBUG
    feign.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Feign (Spring Cloud)
feign:
  client:
    config:
      default:
        logger-level: FULL
        connect-timeout: 5000 # ms
        read-timeout: 15000 # ms

# Resilience4j (Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50 # %
        wait-duration-in-open-state: 30000 # ms
        slow-call-rate-threshold: 50 # %
        slow-call-duration-threshold: 3000 # ms
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 2000 # ms

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  adapter:
    alphavantage:
      url: ${EXT_ALPHAVANTAGE_URL:https://www.alphavantage.co}
      apiKey: ${EXT_ALPHAVANTAGE_API_KEY}
      retry:
        attempts: ${EXT_ALPHAVANTAGE_RETRY_ATTEMPTS:3}
        delay: ${EXT_ALPHAVANTAGE_RETRY_DELAY:2000}