apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-mate-deployment
  namespace: currency-mate-namespace
  labels:
    app: currency-mate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-mate
  template:
    metadata:
      labels:
        app: currency-mate
    spec:
      imagePullSecrets:
        - name: artifact-registry-secret
      serviceAccountName: currency-mate-account
      containers:
        - name: currency-mate-srv
          image: us-central1-docker.pkg.dev/currency-mate-project/currency-mate-docker-images/currency-mate-srv:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "currency-mate-secret-provider"