apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: currency-mate-secret-provider
  namespace: currency-mate-namespace
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/currency-mate-project/secrets/ext-alphavantage-api-key/versions/latest"
        path: "ext-alphavantage-api-key"
      - resourceName: "projects/currency-mate-project/secrets/ext-exchangerate-api-key/versions/latest"
        path: "ext-exchangerate-api-key"
  secretObjects:
    - secretName: currency-mate-secrets
      type: Opaque
      data:
        - objectName: ext-alphavantage-api-key
          key: EXT_ALPHAVANTAGE_API_KEY
        - objectName: ext-exchangerate-api-key
          key: EXT_EXCHANGERATE_API_KEY

