apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency-mate-account
  namespace: currency-mate-namespace
  annotations:
    iam.gke.io/gcp-service-account: currency-mate-account@currency-mate-project.iam.gserviceaccount.com
  labels:
    app: currency-mate